#通用配置（这些配置是没有必要放到apollo去的固定配置[或者增加可读性的配置]，如果容易变动的配置，最好放到apollo里进行配置）

server:
  context-path: /wx
  port: 11133
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
      min-response-size: 2048
#替换Tomcat容器，性能更优
  undertow:
    io-threads: 8
    worker-threads: 248
    buffer-size: 1024


spring:
  ### 项目基本信息
  application:
   #pom中配置
    name: "${server_name}"
  profiles:
    #### 只有设置active属性，才会在开发环境加载dev的配置，default：dev不会加载下方配置   最上层pom中
    active: ${project.environment}
  session:
     store-type: redis
     redis:
       namespace: "${server_name}"
  ### http配置
  http:
    encoding:
      charset: UTF-8
      force: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.huatu.common.jpa.core.CustomDialect

  ### jackson配置
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  mvc:
    throw-exception-if-no-handler-found: true
    #### 只允许通过static目录静态资源访问，这样不会有默认的RecourseHandler,而导致无法正常404抛出异常
    #### 使用之后，springboot默认的资源根路径，都需要添加/static前缀
    static-path-pattern: /static/**

  ### freemarker配置
#  freemarker:
#    preferFileSystemAccess: true
#    cache: true
#    prefix: classpath:/templates
#    suffix: .ftl
#    content-type: text/html; charset=UTF-8
    # settings:  # 这是一个map,注入到factory的settings中

#log日志打印颜色支持
  output:
    ansi:
      enabled: always
#  data:
#    rest:
#      base-path: /admin

logging:
  config: "classpath:config/log4j2-${spring.profiles.active}.xml"

## 监控
info:
  app:
    name: "${server_name}"
    encoding: UTF-8

# 部分监控指标配置已移到配置中心，方便后期统一管理


## spring cloud相关
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 默认超时时间

endpoints:
  actuator:
    enabled: true
  jmx:
    enabled: false
management:
  info.git.mode: full
  security:
    enabled: false
  context-path: /_monitor
  add-application-context-header: false

security:
  basic:
    authorize-mode: none


## 自定义配置

htonline:
## 开启ResponseBodyAdvice
  wrapper.enabled: false
  httpclient.enabled: false
  okhttp.enabled: true
  executor.enabled: true
  degrade.basePackage: com.huatu.tiku
  cache-manage:
    enabled: true
    basePackage: com.huatu.tiku
    prefix:
      redis: "${spring.application.name}"



# 不同环境的不同配置，也可以放在apollo，除了开发使用的特殊debug等配置，一般不建议放在这里
---
spring:
  profiles: dev

server:
  error:
    include-stacktrace: always
debug: true

---
spring:
  profiles: test

server:
  error:
    include-stacktrace: always
---
spring:
  profiles: release

---
spring:
  profiles: product


  http:
    multipart:
      max-file-size: 2MB
      resolve-lazily: true
